version: 2

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wslint

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ldflags:
      - -s -w -X main.version={{.Version}}

    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: 386

archives:
  - format: tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

snapshot:
  version_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
