---
version: '3.7'

services:
  devenv:
    image: idelchi/devenv:dev
    container_name: devenv
    hostname: devenv
    ports:
      # <host:container>
      - '8888:8888' # GoDoc
      - '10000-10200:10000-10200' # Go Profilers
    network_mode: bridge
    user: user
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
