---
version: '3.7'

services:
  devenv:
    build:
      context: ${DEVENV} # or pointing to the location ($DEVENV)
    pull_policy: never
    image: devenv:local
    container_name: devenv
    hostname: devenv
    ports:
      # <host:container>
      - '8888:8888' # GoDoc
      - '10000-10200:10000-10200' # Go Profilers
      - '9090:6419' # grip
    network_mode: bridge
    user: user
    volumes:
      - .:/home/user/ws
    #   - ${DEVENV}:${DEVENV} # Possible to mount it inside
    # environment:
    #   - DEVENV=${DEVENV} # Inherit the environment
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
