version: '3'

vars:
  SETTINGS_DIR: .devenv

includes:
  common:
    taskfile: '{{.SETTINGS_DIR}}/Taskfile.yml'
    vars:
      CONFIG_DIR: '{{.SETTINGS_DIR}}/config'
      SCRIPTS_DIR: '{{.SETTINGS_DIR}}/scripts'
    aliases:
      - ci

  go:
    taskfile: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.go.yml'
    vars:
      CONFIG_DIR: '{{.SETTINGS_DIR}}/config'
      SCRIPTS_DIR: '{{.SETTINGS_DIR}}/scripts'
      COVERAGE: 96.8%

silent: true

output: prefixed

tasks:
  clean:
    - task: common:aux:clean
    - task: go:clean

  info:
    - task: common:git

  format:
    - task: common:format
    - task: go:format

  lint:
    deps:
      - common:lint
      - go:lint

  build:
    - task: go:build
    - task: go:release

  test:
    - task: go:quality
    - task: go:coverlines

  docker:
    - task: common:docker

  all:
    desc: run all available tasks
    cmds:
      - task: clean
      - task: info
      - task: format
      - task: lint
      - task: build
      - task: test

  default:
    desc: clean, format & lint
    cmds:
      - task: info
      - task: format
      - task: lint

  push:
    - task: common:push

  update:
    - task: common:git:update
