name: wslint
on: [push, workflow_dispatch]

env:
  IMAGE: idelchi/devenv:dev

jobs:
  info:
    runs-on: ubuntu-22.04
    container: ${{ env.IMAGE }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task info

  lint:
    needs: info
    runs-on: ubuntu-22.04
    container: ${{ env.IMAGE }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task lint

  test:
    needs: info
    runs-on: ubuntu-22.04
    container: ${{ env.IMAGE }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task test

  build:
    needs: info
    runs-on: ubuntu-22.04
    container: ${{ env.IMAGE }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task build
